### ISSUE TITLE
software name

### ISSUE THREAD

**Issue by edoddridge** [EnvModellingGroup/hrds#15]
Submitted as part of a [review for JOSS](https://github.com/openjournals/joss-reviews/issues/1112).

Is it `hrds` or `hdrs`? The repo is `hdrs`, but the directory name and JOSS paper both suggest `hrds`.

**Comment by jhill1** [comment]
It should be HRDS. I've altered the repo name (I changed my mind in the naming and clearly forgot the actual repo!).

**Comment by jhill1** [comment]
Fixed in #17
