### ISSUE TITLE
TypeError: 'module'

### ISSUE THREAD

**Issue by klaatujk** [EnvModellingGroup/hrds#34]
I am very new in hrds with python, but trying to use hrds to make real bathymetry data.

I followed the instruction for installing hrds using python3 in Ubuntu 20.04 but I got the following error.

Is anybody giving suggestions or comments?
I appreciate you if you give it.

Traceback (most recent call last):
  File "exxyz.py", line 11, in <module>
    bathy = hrds("gebco_uk.tif",rasters=("emod_utm.tif","inspire_data.tif"),distances=(700, 200))
TypeError: 'module' object is not callable

**Comment by jhill1** [comment]
Hello,

Looks like you did 

`import hrds`

So you'll need:

`bathy = hrds.hrds("gebco_uk.tif",rasters=("emod_utm.tif","inspire_data.tif"),distances=(700, 200))`

To call the function hrds inside the module.

**Comment by klaatujk** [comment]
Thank you, but I got the error again.
Do you have any idea?

Traceback (most recent call last):
  File "exxyz.py", line 11, in <module>
    bathy = hrds.hrds("gebco_uk.tif",rasters=("emod_utm.tif","inspire_data.tif"),distances=(700, 200))
AttributeError: module 'hrds.hrds' has no attribute 'hrds'

**Comment by jhill1** [comment]
Apologies, it should be capitalised:

`Bathy = hrds.HRDS(...)`

I need to update the first example on the Readme
